builders:
  testBuilder:
    import: "package:code_gen_test/test_generator.dart"
    builder_factories: ["testBuilder"]
    build_extensions: {".dart": [".g.part"]}
    auto_apply: root_package
    build_to: source